FROM haskell:8

WORKDIR /opt/haskell-contracts
RUN cabal update

# Add just the .cabal file to capture dependencies
COPY ./contracts.cabal /opt/haskell-contracts/contracts.cabal

# Docker will cache this command as a layer, freeing us up to
# modify source code without re-installing dependencies
# (unless the .cabal file changes!)
RUN cabal build --only-dependencies -j4

# Add and Install Application Code
COPY . /opt/haskell-contracts
RUN cabal install
RUN apt-get update && apt-get install -y nginx
ENTRYPOINT ["nginx", "-g", "daemon off;"]
